{"name": "test_valid_auth[problem_user-secret_sauce]", "status": "broken", "statusDetails": {"message": "TypeError: 'str' object is not callable", "trace": "self = <tests.test_auth.TestAuth object at 0x0000012C05DF0A60>, email = 'problem_user', password = 'secret_sauce'\napp = <pages.application.Application object at 0x0000012C06852B80>\n\n    @allure.story(\"Авторизация\")\n    @allure.severity(\"blocker\")\n    @pytest.mark.parametrize(\n        \"email, password\",\n        (\n                (Users.STANDARD_USERNAME, Users.PASSWORD),\n                (Users.PROBLEM_USERNAME, Users.PASSWORD),\n                (Users.PER_GLITCH_USERNAME, Users.PASSWORD)\n        ),\n    )\n    def test_valid_auth(self, email, password, app):\n        \"\"\"\n        1. Открыть страницу\n        2. Ввести валидные значения в поля логина и пароля\n        3. Нажать кнопку LOGIN\n        4. Проверить, что в бургере есть кнопка Logout\n        \"\"\"\n        app.open_main_page()\n        app.login.auth(email, password)\n    \n>       assert (app.main_page.logout_button_text() ==\n                ButtonTexts.LOGOUT_BUTTON_TEXT, \"Кнопка Logout не найдена\")\n\ntests\\test_auth.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.main_page.MainPage object at 0x0000012C05EA2E20>\n\n    def logout_button_text(self):\n>       self.logout_button().text()\nE       TypeError: 'str' object is not callable\n\npages\\main_page.py:42: TypeError"}, "description": "\n        1. Открыть страницу\n        2. Ввести валидные значения в поля логина и пароля\n        3. Нажать кнопку LOGIN\n        4. Проверить, что в бургере есть кнопка Logout\n        ", "attachments": [{"name": "screenshot", "source": "69948c32-8eff-4e8c-b1b3-f3c101f7c492-attachment.png", "type": "image/png"}, {"name": "log", "source": "073d80a2-93b7-4b6f-9704-30c337f6b9cd-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "e65bb59c-0615-4e5a-8dc3-f11e50b1ed97-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "email", "value": "'problem_user'"}, {"name": "password", "value": "'secret_sauce'"}], "start": 1615012531464, "stop": 1615012532073, "uuid": "b06f507c-172c-4be2-8d4f-570dade100c0", "historyId": "09a66511e2a96dc6fce688ddebb865f0", "testCaseId": "52b3ff36bc4dce34c6b761d4e4c54109", "fullName": "tests.test_auth.TestAuth#test_valid_auth", "labels": [{"name": "severity", "value": "blocker"}, {"name": "story", "value": "Авторизация"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "LAPTOP-Q6599UFH"}, {"name": "thread", "value": "9404-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}
