{"name": "test_valid_auth[problem_user-secret_sauce]", "status": "failed", "statusDetails": {"message": "AssertionError: Кнопка Logout не найдена\nassert None == 'Logout'\n +  where None = <bound method MainPage.logout_button_text of <pages.main_page.MainPage object at 0x000002664A4C4B80>>()\n +    where <bound method MainPage.logout_button_text of <pages.main_page.MainPage object at 0x000002664A4C4B80>> = <pages.main_page.MainPage object at 0x000002664A4C4B80>.logout_button_text\n +      where <pages.main_page.MainPage object at 0x000002664A4C4B80> = <pages.application.Application object at 0x000002664A4FA4C0>.main_page\n +  and   'Logout' = ButtonTexts.LOGOUT_BUTTON_TEXT", "trace": "self = <tests.test_auth.TestAuth object at 0x000002664A4CF5E0>, email = 'problem_user', password = 'secret_sauce'\napp = <pages.application.Application object at 0x000002664A4FA4C0>\n\n    @allure.story(\"Авторизация\")\n    @allure.severity(\"blocker\")\n    @pytest.mark.parametrize(\n        \"email, password\",\n        (\n            (Users.STANDARD_USERNAME, Users.PASSWORD),\n            (Users.PROBLEM_USERNAME, Users.PASSWORD),\n            (Users.PER_GLITCH_USERNAME, Users.PASSWORD),\n        ),\n    )\n    def test_valid_auth(self, email, password, app):\n        \"\"\"\n        1. Открыть страницу\n        2. Ввести валидные значения в поля логина и пароля\n        3. Нажать кнопку LOGIN\n        4. Проверить, что в бургере есть кнопка Logout\n        \"\"\"\n        app.open_main_page()\n        app.login.auth(email, password)\n>       assert (\n            app.main_page.logout_button_text() == ButtonTexts.LOGOUT_BUTTON_TEXT\n        ), \"Кнопка Logout не найдена\"\nE       AssertionError: Кнопка Logout не найдена\nE       assert None == 'Logout'\nE        +  where None = <bound method MainPage.logout_button_text of <pages.main_page.MainPage object at 0x000002664A4C4B80>>()\nE        +    where <bound method MainPage.logout_button_text of <pages.main_page.MainPage object at 0x000002664A4C4B80>> = <pages.main_page.MainPage object at 0x000002664A4C4B80>.logout_button_text\nE        +      where <pages.main_page.MainPage object at 0x000002664A4C4B80> = <pages.application.Application object at 0x000002664A4FA4C0>.main_page\nE        +  and   'Logout' = ButtonTexts.LOGOUT_BUTTON_TEXT\n\ntests\\test_auth.py:31: AssertionError"}, "description": "\n        1. Открыть страницу\n        2. Ввести валидные значения в поля логина и пароля\n        3. Нажать кнопку LOGIN\n        4. Проверить, что в бургере есть кнопка Logout\n        ", "attachments": [{"name": "screenshot", "source": "b1cc974f-f361-4e48-b2a3-7e0eefa58b9e-attachment.png", "type": "image/png"}, {"name": "log", "source": "f1478456-1b5e-4e1b-82e4-7945accaed67-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "9fe5dfe6-7d64-4a7f-9efd-c391b6c6ff94-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "email", "value": "'problem_user'"}, {"name": "password", "value": "'secret_sauce'"}], "start": 1615299376838, "stop": 1615299377885, "uuid": "0b407cf9-2c40-4edb-b6a3-0214349f004e", "historyId": "09a66511e2a96dc6fce688ddebb865f0", "testCaseId": "52b3ff36bc4dce34c6b761d4e4c54109", "fullName": "tests.test_auth.TestAuth#test_valid_auth", "labels": [{"name": "severity", "value": "blocker"}, {"name": "story", "value": "Авторизация"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "LAPTOP-Q6599UFH"}, {"name": "thread", "value": "19868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}
